version: "3"
services:
  app:
    env_file:
      - .env
    container_name: pixera_backend
    restart: always
    build: .
    environment:
      DB_HOST: postgres
      MEILI_HOST: http://meilisearch:7700
    ports:
      - "$PORT:$PORT"
    depends_on:
      postgres:
        condition: service_healthy
      meilisearch: {}
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - .env
    links:
      - postgres
  meilisearch:
    image: getmeili/meilisearch
    hostname: meilisearch
    container_name: meilisearch
    environment:
      MEILI_ENV: development
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch:/meili_data
    ports:
      - "7701:7700"
    restart: always
volumes:
  postgres:
    driver: local
  meilisearch:
    driver: local
